### ISSUE TITLE
`SubmitParamChangeProp` fails after `testPowerSwing`

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/poa#66]
if we move testUpdatePOAParams to be last in the e2e test, the last gov vote fails for not enough votes (prop status 4).

Assumption:
- This bug happens if we do a gov prop and vals vote on it after testPowerSwing is used.

I also did do a **large** power swing right before this, maybe the lesser validator only had enough time to get in the vote?

```
proposal:
  deposit_end_time: "2023-11-08T05:16:26.688900936Z"
  failed_reason: proposal did not get enough votes to pass
  final_tally_result:
    abstain_count: "0"
    no_count: "0"
    no_with_veto_count: "0"
    yes_count: "1000000"
  id: "2"
  messages:
  - type: /strangelove_ventures.poa.v1.MsgUpdateParams
    value:
      params:
        admins:
        - cosmos1hj5fveer5cjtn4wd6wstzugjfdxzl0xpxvjjvr
        - cosmos10d07y265gmmuvt4z0w9aw880jnsr700j6zn9kn
        - cosmos1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqnrql8a
      sender: cosmos10d07y265gmmuvt4z0w9aw880jnsr700j6zn9kn
  metadata: ipfs://CID
  proposer: cosmos1wthvepgealr9gnltv68kw4acdldzjdm3ha57v7
  status: 4
  submit_time: "2023-11-08T05:16:16.688900936Z"
  summary: params
  title: UpdateParams
  total_deposit:
  - amount: "50"
    denom: stake
  voting_end_time: "2023-11-08T05:16:31.688900936Z"
  voting_start_time: "2023-11-08T05:16:16.688900936Z"
```
